server:
  port: 6767
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: EUREKA-SERVER
  config:
    import: optional:configserver:http://localhost:6666/